export const sampleNews = [
    {
        id: '1890370',
        title: 'Tesla goes bankurpt',
        author: 'Times of Indian Ocean',
        section: 'news',
        slug: 'tesla-goes-bankurpt',
        url: 'http://www.google.com',
        thumbnail: '',
    },
    {
        id: '35315361',
        title: 'Lillies are the best flowers in the world',
        author: 'TV9 South Africa',
        section: 'news',
        slug: 'lillies-best-flower',
        url: 'http://www.google.com',
        thumbnail: '',
    },
    {
        id: '357374624',
        title: 'Bangaluru Bulls win Indian Pro Kabaddi League',
        author: 'Sports Mandya',
        section: 'spots',
        slug: 'bb-win',
        url: 'http://www.google.com',
        thumbnail: '',
    },
    {
        id: '462642573',
        title: 'RCB Wins IPL after 25 Years of Straight Losses',
        author: 'Orange News Network',
        section: 'sports',
        slug: 'something',
        url: 'http://www.google.com',
        thumbnail: '',
    },
    {
        id: '135462465',
        title: 'Kaveri River is flowing nicely',
        author: 'Times of Indian Ocean',
        section: 'news',
        slug: 'kaveri-river',
        url: 'http://www.google.com',
        thumbnail: '',
    },
    {
        id: '64735535',
        title: 'React js lmao lmao lmao lmao',
        author: 'Times of Indian Ocean',
        section: 'news',
        slug: 'kaveri-river',
        url: 'http://www.google.com',
        thumbnail: '',
    },
];

export const news = [
    {
        title: 'Bitcoin bull Michael Saylor says MicroStrategy will continue to use cash, debt, or equity to keep adding to its trove of bitcoin',
        author: 'insider@insider.com (Carla Mozée)',
        published_date: '2021-11-01 18:38:11',
        published_date_precision: 'timezone unknown',
        link: 'https://markets.businessinsider.com/news/currencies/microstrategy-bitcoin-cryptocurrency-buying-inflation-ceo-michael-saylor-mstr-holdings-2021-11',
        clean_url: 'businessinsider.com',
        excerpt:
            "MicroStrategy's stash of bitcoin is now worth around $7 billion after an additional 9,000 coins were added in the quarter ended Sept. 30.",
        summary:
            "MicroStrategy CEO Michael Saylor.\nJoe Raedle/Getty Images\n\nMicroStrategy will continue stockpiling bitcoin for years to come, and while the cryptocurrency's price is volatile, \"it's going up forever,\" CEO Michael Saylor told CNBC on Monday. The bitcoin bull outlined his bullish outlook on the digital asset after a MicroStrategy regulatory filing last week showed the company bought 9,000 bitcoin in the quarter ended Sept. 30. The data analytics company's bitcoin count stood at 114,042, and the stash was worth nearly $7 billion on Monday as bitcoin traded around $61,220.",
        rights: 'Insider',
        rank: 110,
        topic: 'business',
        country: 'US',
        language: 'en',
        authors: ['Carla Mozée'],
        media: 'https://images2.markets.businessinsider.com/618013b01037b100181533c6?format=jpeg',
        is_opinion: false,
        twitter_account: null,
        _score: 9.532086,
        _id: '63f9468b36e13bd07887e756af1bbcfd',
    },
    {
        title: 'Whoever tells you that lightning is not the real Bitcoin',
        author: '/u/TonyStark028',
        published_date: '2021-11-01 19:09:02',
        published_date_precision: 'full',
        link: 'https://www.reddit.com/r/Bitcoin/comments/qkl7re/whoever_tells_you_that_lightning_is_not_the_real',
        clean_url: 'reddit.com',
        excerpt:
            'just tired of that already submitted by /u/TonyStark028 [link] [comments]',
        summary:
            'A community dedicated to Bitcoin, the currency of the Internet. Bitcoin is a distributed, worldwide, decentralized digital money. Bitcoins are issued and managed without any central authority whatsoever: there is no government, company, or bank in charge of Bitcoin. You might be interested in Bitcoin if you like cryptography, distributed peer-to-peer systems, or economics. A large percentage of Bitcoin enthusiasts are libertarians, though people of all political philosophies are welcome.',
        rights: 'reddit.com',
        rank: 38,
        topic: 'finance',
        country: 'US',
        language: 'en',
        authors: ['/u/TonyStark028'],
        media: 'https://www.redditstatic.com/desktop2x/img/favicon/apple-icon-57x57.png',
        is_opinion: false,
        twitter_account: '@reddit',
        _score: 9.505016,
        _id: '1bc5b1714fef3281c4b20b749ea3bb41',
    },
    {
        title: 'Ten31 Launches: A New Bitcoin Venture Capitalist Firm',
        author: 'ayite',
        published_date: '2021-11-01 03:15:00',
        published_date_precision: 'timezone unknown',
        link: 'https://article.wn.com/view/2021/10/31/Ten31_Launches_A_New_Bitcoin_Venture_Capitalist_Firm_h/',
        clean_url: 'wn.com',
        excerpt:
            "Ten31 is a new venture fund named after October 31, the birthday of the Bitcoin white paper. The venture fund's ethos is... read full story Photo: Bitcoin Keychain. Report rights infringement <",
        summary:
            "Ten31 is a new venture fund named after October 31, the birthday of the Bitcoin white paper. The venture fund's ethos is... read full story Photo: Bitcoin Keychain. Report rights infringement close Bitcoin is a decentralized electronic cash system that uses peer-to-peer networking, digital signatures and cryptographic proof so as to enable users to conduct irreversible transactions without relying on trust. Nodes broadcast transactions to the network, which records them in a public history, called the blockchain, after validating them with a proof-of-work system.",
        rights: 'wn.com',
        rank: 2336,
        topic: 'news',
        country: 'US',
        language: 'en',
        authors: [],
        media: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Screenshot_of_Bitcoin-qt.png/120px-Screenshot_of_Bitcoin-qt.png',
        is_opinion: false,
        twitter_account: '@worldnewsdotcom',
        _score: 9.474227,
        _id: 'c9a7310b28a8d6c176550b362344a1e6',
    },
    {
        title: 'Bitcoin Is Not Asking For Permission, We Forgot To Do That!',
        author: '/u/HugoRamos',
        published_date: '2021-11-01 00:48:50',
        published_date_precision: 'full',
        link: 'https://www.reddit.com/r/Bitcoin/comments/qk2rf0/bitcoin_is_not_asking_for_permission_we_forgot_to',
        clean_url: 'reddit.com',
        excerpt: 'submitted by /u/HugoRamos [link] [comments]',
        summary:
            'A community dedicated to Bitcoin, the currency of the Internet. Bitcoin is a distributed, worldwide, decentralized digital money. Bitcoins are issued and managed without any central authority whatsoever: there is no government, company, or bank in charge of Bitcoin. You might be interested in Bitcoin if you like cryptography, distributed peer-to-peer systems, or economics. A large percentage of Bitcoin enthusiasts are libertarians, though people of all political philosophies are welcome.',
        rights: 'reddit.com',
        rank: 38,
        topic: 'finance',
        country: 'US',
        language: 'en',
        authors: ['/u/HugoRamos'],
        media: 'https://external-preview.redd.it/TBCR5UhXqlaS7WuQmQJChy6Y2lv6SDRyyodUQgvG2U4.jpg?auto=webp&s=84b791e75ee5c3cfb0c7c0514cb8283665e27fb5',
        is_opinion: false,
        twitter_account: '@reddit',
        _score: 9.47034,
        _id: 'bca4860c02ae9885186b3532474e15a9',
    },
    {
        title: 'NFL legend Aaron Rodgers to take a portion of his salary in Bitcoin : Bitcoin',
        author: '/u/Special_Yam_1174',
        published_date: '2021-11-01 20:11:40',
        published_date_precision: 'full',
        link: 'https://www.reddit.com/r/Bitcoin/comments/qkmmd0/nfl_legend_aaron_rodgers_to_take_a_portion_of_his',
        clean_url: 'reddit.com',
        excerpt: 'submitted by /u/Special_Yam_1174 [link] [comments]',
        summary:
            'A community dedicated to Bitcoin, the currency of the Internet. Bitcoin is a distributed, worldwide, decentralized digital money. Bitcoins are issued and managed without any central authority whatsoever: there is no government, company, or bank in charge of Bitcoin. You might be interested in Bitcoin if you like cryptography, distributed peer-to-peer systems, or economics. A large percentage of Bitcoin enthusiasts are libertarians, though people of all political philosophies are welcome.',
        rights: 'reddit.com',
        rank: 38,
        topic: 'finance',
        country: 'US',
        language: 'en',
        authors: ['/u/Special_Yam_1174'],
        media: 'https://external-preview.redd.it/RmVtQwDpBZdmIJdofOPU5ZiRIKHNCct0gDY3sjFJ3BA.jpg?auto=webp&s=18fe702b1ac1cc05b856fbbcdb0c12fd57bade56',
        is_opinion: false,
        twitter_account: '@reddit',
        _score: 9.464521,
        _id: '0c8a0fce9b951a1fb9be92cab7bd0d6f',
    },
    {
        title: 'Reminder: on this exact day last year, bitcoin was at $13,700.',
        author: '/u/JollyJury',
        published_date: '2021-11-01 23:58:10',
        published_date_precision: 'full',
        link: 'https://www.reddit.com/r/Bitcoin/comments/qkrehz/reminder_on_this_exact_day_last_year_bitcoin_was',
        clean_url: 'reddit.com',
        excerpt:
            "What an incredible year it's been. Through the ups and the downs and the summer of FUD, we managed to enter November over 60k. Just sit back and stare in awe at the 1 year chart. submitted by /u/JollyJury [link] [comments]",
        summary:
            'A community dedicated to Bitcoin, the currency of the Internet. Bitcoin is a distributed, worldwide, decentralized digital money. Bitcoins are issued and managed without any central authority whatsoever: there is no government, company, or bank in charge of Bitcoin. You might be interested in Bitcoin if you like cryptography, distributed peer-to-peer systems, or economics. A large percentage of Bitcoin enthusiasts are libertarians, though people of all political philosophies are welcome.',
        rights: 'reddit.com',
        rank: 38,
        topic: 'finance',
        country: 'US',
        language: 'en',
        authors: ['/u/JollyJury'],
        media: 'https://www.redditstatic.com/desktop2x/img/favicon/apple-icon-57x57.png',
        is_opinion: false,
        twitter_account: '@reddit',
        _score: 9.4609995,
        _id: 'df5b20a0749e16a9564d6277c0c83205',
    },
    {
        title: "Crypto Price Prediction: Bitcoin Could Hit $100,000 Before The End Of 2021—But Lacks Ethereum ‘Intensity'",
        author: 'Billy Bambrough, Senior Contributor',
        published_date: '2021-11-02 09:30:04',
        published_date_precision: 'full',
        link: 'https://www.forbes.com/sites/billybambrough/2021/11/02/crypto-price-prediction-bitcoin-could-hit-100000-before-the-end-of-2021-but-lacks-ethereum-intensity/',
        clean_url: 'forbes.com',
        excerpt:
            'Despite the huge gains made by bitcoin and ethereum already this year, many investors expect prices to continue to climb, with one crypto executive predicting the bitcoin price will hit $100,000…',
        summary:
            "Bitcoin, after storming through much of October, has somewhat come off the boil with the bitcoin price falling back from highs of around $67,000. Subscribe now to Forbes' CryptoAsset & Blockchain Advisor and discover hot new NFT and crypto blockbusters poised for 1,000% gains The bitcoin price has doubled since its summer lows, while ethereum, the second-largest cryptocurrency after bitcoin, has added around 140%—hitting an all-time high last week. Despite the huge gains made by bitcoin and ethereum already this year, many investors expect prices to continue to climb, with one crypto executive predicting the bitcoin price will hit $100,000 before the end of 2021.",
        rights: 'Copyright 2021 Forbes Media LLC',
        rank: 51,
        topic: 'business',
        country: 'US',
        language: 'en',
        authors: [
            'Billy Bambrough, Senior Contributor',
            'Billy Bambrough, Senior Contributor',
        ],
        media: 'https://thumbor.forbes.com/thumbor/fit-in/1200x0/filters%3Aformat%28jpg%29/https%3A%2F%2Fspecials-images.forbesimg.com%2Fimageserve%2F1214132428%2F0x0.jpg',
        is_opinion: false,
        twitter_account: '@forbes',
        _score: 9.45668,
        _id: 'b91641d151e898e29159d5b845475c5e',
    },
    {
        title: 'Aaron Rodgers to take a part of his 2021 salary in Bitcoin, give $1 million of digital currency to fans',
        author: 'Emmett Prosser',
        published_date: '2021-11-02 02:51:13',
        published_date_precision: 'full',
        link: 'https://www.usatoday.com/story/sports/nfl/packers/2021/11/01/packers-aaron-rodgers-takes-portion-his-salary-bitcoin/6244838001/',
        clean_url: 'usatoday.com',
        excerpt:
            "Aaron Rodgers announced he's taking a portion of his NFL salary in\\u00a0Bitcoin.\\u00a0And he's giving $1 million away in the digital currency to his fans.",
        summary:
            "NFC Week 8 overreactions: Cooper Rush, Cowboys continue to show a championship mentalityMackenzie Salmon 'overreacts' to the biggest storylines in the NFC after Week 8 action in the NFL.Green Bay Packers quarterback Aaron Rodgers is the latest professional athlete to join the cryptocurrency rage. And he's giving a chunk of the digital loot away to his fans.In a Twitter post Monday afternoon, Rodgers announced he had teamed with Cash App to take a portion of his NFL salary in Bitcoin. \"Bitcoin to the moon,\" Rodgers exclaimed.",
        rights: 'Copyright 2021, GANNETT',
        rank: 126,
        topic: 'news',
        country: 'US',
        language: 'en',
        authors: ['Packers News', 'Emmett Prosser, Packers News'],
        media: 'https://www.gannett-cdn.com/presto/2021/10/24/PPAN/5433e090-aa31-4466-a19e-8306ebfc4a7f-packers25_10.jpg?auto=webp&crop=4204,2365,x0,y174&format=pjpg&width=1200',
        is_opinion: false,
        twitter_account: '@usatoday',
        _score: 9.449431,
        _id: '3d8862e2f9e013abb2c7b2a7c4e471bb',
    },
    {
        title: 'Bitcoin in celebratory mood as a big week ahead looms for financial markets',
        author: 'Crypto AM Daily in association with Luno',
        published_date: '2021-11-01 11:34:11',
        published_date_precision: 'full',
        link: 'https://www.cityam.com/bitcoin-in-celebratory-mood-as-a-big-week-ahead-looms-for-financial-markets/',
        clean_url: 'cityam.com',
        excerpt:
            'Bitcoin is up two per cent over the last 24 hours to just above the £62k mark, while Ethereum is also up 1.5 per cent to just above $4,300.',
        summary:
            "Yesterday marked the 13th birthday of the Bitcoin (BTC) white paper, a monumental moment in cryptocurrency (and world) history. The whitepaper arrived in the inboxes of a cryptography mailing list hosted by Metzdow at approximately 2pm Eastern Time. In the email, which is maintained by the Nakamato Institute, Bitcoin's pseudonymous creator, Satoshi Nakamoto, wrote: 'I've been working on a new electronic cash system that's fully peer-to-peer, with no trusted third party.'  The rest, as they say, is history.",
        rights: 'cityam.com',
        rank: 3842,
        topic: 'finance',
        country: 'GB',
        language: 'en',
        authors: ['Crypto AM Daily in association with Luno'],
        media: 'https://www.cityam.com/wp-content/uploads/2021/10/crypto-am-daily.jpeg',
        is_opinion: false,
        twitter_account: null,
        _score: 9.425244,
        _id: '06706840ccb1af4a8fc6de10cb5ceb60',
    },
    {
        title: 'Aaron Rodgers teams with Square in $1 million bitcoin giveaway promotion',
        author: 'Mike Murphy',
        published_date: '2021-11-02 01:39:00',
        published_date_precision: 'full',
        link: 'https://www.marketwatch.com/story/aaron-rodgers-teams-with-square-in-1-million-bitcoin-giveaway-promotion-11635817152',
        clean_url: 'marketwatch.com',
        excerpt:
            'Green Bay Packers quarterback Aaron Rodgers will collect part of his salary in bitcoin, and will give away $1 million in bitcoin as part of a promotion with...',
        summary:
            "Green Bay Packers quarterback Aaron Rodgers will collect part of his salary in bitcoin, and will give away $1 million in bitcoin as part of a promotion with Square Inc.'s SQ, +0.21% Cash App. 'I believe in Bitcoin & the future is bright,' Rodgers said in a tweet Monday. 'That's why I'm teaming up with Cash App to take a portion of my salary in bitcoin today.' In a Halloween-themed video dressed as a John Wick, he also announced the crypto giveaway: 'Bitcoin is a new concept, it can be intimidating.",
        rights: 'marketwatch.com',
        rank: 279,
        topic: 'news',
        country: 'US',
        language: 'en',
        authors: ['Mike Murphy'],
        media: 'https://images.mktw.net/im-427319/social',
        is_opinion: false,
        twitter_account: '@mmmmurf',
        _score: 9.41243,
        _id: '3ce96224b155bd6eec4632ac1f59d7df',
    },
    {
        title: 'Bitcoin (BTC) Closes Month Above $60,000 for First Time in History',
        author: '/u/whiteyfisk46',
        published_date: '2021-11-01 19:09:12',
        published_date_precision: 'full',
        link: 'https://www.reddit.com/r/Bitcoin/comments/qkl7wn/bitcoin_btc_closes_month_above_60000_for_first',
        clean_url: 'reddit.com',
        excerpt: 'submitted by /u/whiteyfisk46 [link] [comments]',
        summary:
            'A community dedicated to Bitcoin, the currency of the Internet. Bitcoin is a distributed, worldwide, decentralized digital money. Bitcoins are issued and managed without any central authority whatsoever: there is no government, company, or bank in charge of Bitcoin. You might be interested in Bitcoin if you like cryptography, distributed peer-to-peer systems, or economics. A large percentage of Bitcoin enthusiasts are libertarians, though people of all political philosophies are welcome.',
        rights: 'reddit.com',
        rank: 38,
        topic: 'finance',
        country: 'US',
        language: 'en',
        authors: ['/u/whiteyfisk46'],
        media: 'https://external-preview.redd.it/xYxCokDXv-r1xOSQ2WH9kg_JHEuur8gNsYzPEioUItk.jpg?auto=webp&s=e04a9945bd3d95813e0d81891334513d09ff3e05',
        is_opinion: false,
        twitter_account: '@reddit',
        _score: 9.402596,
        _id: 'd6e3bb340b45a6a21ce7b4a42cbacf33',
    },
    {
        title: 'Why bitcoin is looking more like a pyramid scheme',
        author: null,
        published_date: '2021-11-01 05:01:30',
        published_date_precision: 'full',
        link: 'https://www.scmp.com/comment/opinion/world/article/3154210/why-bitcoin-looking-more-pyramid-scheme-and-central-banks',
        clean_url: 'scmp.com',
        excerpt:
            'Bitcoin is looking more like a pyramid scheme every day since the recent launch of a US bitcoin exchange traded fund. ETFs have the potential to lure billions of dollars into bitcoin, allowing…',
        summary:
            "Bitcoin is looking more like a pyramid scheme every day since the recent launch of a US bitcoin exchange traded fund. ETFs have the potential to lure billions of dollars into bitcoin, allowing investors and speculators who got in at the bottom to get out at the top, before the pyramid collapses. This renders the case for official regulation of bitcoin and other cryptocurrencies, and the launch of central bank digital currencies such as China's proposed digital yuan, all the more urgent and compelling, before too many people become casualties of the prospective collapse.",
        rights: 'asiaone.com',
        rank: 577,
        topic: 'finance',
        country: 'HK',
        language: 'en',
        authors: [],
        media: 'https://media.asiaone.com/sites/default/files/styles/a1_600x316/public/original_images/Nov2021/20211101_bitcoin_pexels.jpg?h=0429cc9e&itok=Ow44aHV_',
        is_opinion: false,
        twitter_account: '@asiaonecom',
        _score: 9.390392,
        _id: '7dadd82b60503616a2df52c7cac46efd',
    },
];
